server:
  port: 9372
  servlet:
    context-path: /provider

spring:
  session:
    redis:
      repository-type: indexed
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr:
        username:
        password:
  data:
    redis:
      password:
      port:
      host:

logging:
  level:
    pers.project.api: info
    org.apache.ibatis: info
  file:
    path: /docker/project/provider/log
  logback:
    rollingpolicy:
      max-history: 15