server:
  port: 8123
  servlet:
    context-path: /facade

spring:
  session:
    redis:
      repository-type: indexed
  application:
    name: facade
  cloud:
    nacos:
      discovery:
        server-addr:
        username:
        password:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:/api-facade?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    username:
    password:
    hikari:
      # 连接池空闲连接的最小数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认 600000（ 10 分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是 10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为，默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: hikariDataSource
      # 此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000，即 30 分钟
      max-lifetime: 900000
      # 数据库连接超时时间，默认 30 秒，即 30000
      connection-timeout: 30000
  data:
    redis:
      password:
      port:
      host:

rocketmq:
  name-server:
  producer:
    group: facade-group

logging:
  level:
    pers.project.api: info
    org.apache.ibatis: info
#  file:
#    path: /docker/project/facade/log
#  logback:
#    rollingpolicy:
#      max-history: 15

springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: pers.project.api.facade.controller